config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :empleados, only: [:index, :show]
  resources :productos, only: [:index, :show]
  resources :proveedores, only: [:index]
  resources :pedidos, only: [:new, :create, :show]
  resources :detalle_pedidos, only: [:show]

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/detalle_pedido.rb
class DetallePedido < ApplicationRecord
  belongs_to :pedido
  belongs_to :producto
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :empleado
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :proveedor
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def index
    @clientes = Cliente.all   #Mostrar todos los clientes
  end

  def show    #Detalles de un cliente
    @cliente = Cliente.find(params[:id])   #Busca mediante id del cliente
  end

  def new    #Creación de nuevo cliente
    @cliente = Cliente.new
  end

  def create   #Crea y guarda nuevo cliente
    @cliente = Cliente.new(cliente_params)
    if @cliente.save
      redirect_to clientes_path  #redirige a la página de clientes
    else
      render :new  #si falla vuelve al mismo forulario de creacion
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])   # Encuentra el cliente usando :id para su edición
  end

  def update
    @cliente = Cliente.find(params[:id])  # Encuentra el cliente usando :id y lo asigna a @cliente
    if @cliente.update(cliente_params)  # Intenta actualizar el cliente con los nuevos datos del formulario
      redirect_to @cliente   # Redirige al cliente específico si la actualización es exitosa
    else
      render :edit   # Si la actualización falla, vuelve al formulario de edición
    end
  end

 

  private

  def cliente_params   # Método privado para definir los parámetros permitidos para Cliente

    # Requiere que los datos del formulario contengan un objeto :cliente y permite los campos especificados
    params.require(:cliente).permit(:nombre, :apellido, :telefono, :dni, :email) 
  end
end

app/controllers/detalle_pedidos_controller.rb
class DetallePedidosController < ApplicationController
    def show
        @detalle_pedido = DetallePedido.find(params[:id])
        @pedido = @detalle_pedido.pedido
        @cliente = @pedido.cliente
        @empleado = @pedido.empleado
        @producto = @pedido.producto
    end
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  def index
    @empleados = Empleado.select(:id, :nombre, :cargo)  # Solo selecciona los campos necesarios
  end

  # Acción para mostrar todos los detalles del empleado seleccionado
  def show
    @empleado = Empleado.find(params[:id])
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  def new
    @pedido = Pedido.new  # inicializa una nueva instancia de Pedido
    @productos = Producto.all #carga todos los productos disponibles en la variable de instancia @productos
  end

  def create   #Crea nuevo pedido
    @pedido = Pedido.new(pedido_params)
    @producto = Producto.find(@pedido.producto_id)   #Busca el producto y sus datos por Id
    @pedido.precio_unitario = @producto.precio     #Muestra el precio del producto seleccionado
    @pedido.subtotal = @pedido.cantidad * @pedido.precio_unitario

    if @pedido.save
      
      @detalle_pedido = DetallePedido.create(  #Crea un nuevo pedido en la tabla 
        pedido_id: @pedido.id,
        precio_unitario: @pedido.precio_unitario,
        subtotal: @pedido.subtotal
      )
      redirect_to @pedido
    else
      @productos = Producto.all
      render :new
    end
  end

  def show
    @pedido = Pedido.find(params[:id])
    # Cargar el detalle del pedido relacionado
    @detalle_pedido = DetallePedido.find_by(pedido_id: @pedido.id)

    # Cargar registros asociados
    @cliente = Cliente.find(@pedido.cliente_id)
    @empleado = Empleado.find(@pedido.empleado_id)
    @producto = Producto.find(@pedido.producto_id)
  end

  private

  def pedido_params
    params.require(:pedido).permit(:fecha_pedido, :cliente_id, :empleado_id, :producto_id, :cantidad)
    #los parámetros permitidos se utilicen al crear o actualizar un pedido. 
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index   #Mostrar lista de productos
    @productos = Producto.select(:id, :nombre_producto, :precio)
  end

  # Acción para mostrar todos los detalles del producto seleccionado
  def show
    @producto = Producto.find(params[:id])  #Busca mediante su id
  end
end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController
  def index
    @proveedores = Proveedor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/detalle_pedidos_helper.rb
module DetallePedidosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/views/clientes/create.html.erb
<h1>Clientes#create</h1>
<p>Find me in app/views/clientes/create.html.erb</p>

app/views/clientes/edit.html.erb
<%= stylesheet_link_tag 'clientes/clientes_edit', media: 'all' %>
<h1>Editar Datos del Cliente</h1>
<%= form_with model: @cliente, local: true do |form| %>  <!-- Crea un formulario y los llena con los datos del cliente a editar -->
  <div>
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
  <div>
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>
  <div>
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>
  <div>
    <%= form.label :dni %>
    <%= form.text_field :dni %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.submit "Actualizar" %>
  </div>
<% end %>

app/views/clientes/index.html.erb
<%= stylesheet_link_tag 'clientes/clientes_lista', media: 'all' %>   <!-- enlace a estilos -->
<h1>Lista de Clientes</h1>

<%= link_to 'Registrar Nuevo Cliente', new_cliente_path, class: "btn btn-primary" %>   <!-- Link a nuevo cliente -->

<table>
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Teléfono</th>
    <th>DNI</th>
    <th>Email</th>
    <th>Acciones</th>
  </tr>
  <% @clientes.each do |cliente| %>   <!-- Muestra todo los clientes que hay registrados en la tabla cliente -->
    <tr>
      <td><%= cliente.id %></td>
      <td><%= cliente.nombre %></td>
      <td><%= cliente.apellido %></td>
      <td><%= cliente.telefono %></td>
      <td><%= cliente.dni %></td>
      <td><%= cliente.email %></td>
      <td>
        <%= link_to 'Ver Detalles', cliente_path(cliente), class: "btn btn-info" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/clientes/new.html.erb
<%= stylesheet_link_tag 'clientes/clientes_new', media: 'all' %>   <!-- enlace a estilos -->

<h1>Registrar Nuevo Cliente</h1>

<%= form_with(model: @cliente, local: true) do |form| %>   <!-- Inicia un nuevo formulario para guardar en cliente -->
  

  <div class="form-group">             <!-- Campos del formulario -->
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group">     
    <%= form.label :apellido %>
    <%= form.text_field :apellido, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :dni %>
    <%= form.text_field :dni, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="actions">                 <!-- Enviar formulario -->
    <%= form.submit 'Registrar Cliente', class: "btn btn-success" %>
  </div>
<% end %>

<%= link_to 'Volver a la lista de Clientes', clientes_path, class: "btn btn-secondary" %>

app/views/clientes/show.html.erb
<%= stylesheet_link_tag 'clientes/clientes_detalles', media: 'all' %>

<h1>Datos del Cliente</h1>
<p><strong>Nombre:</strong> <%= @cliente.nombre %></p>
<p><strong>Apellido:</strong> <%= @cliente.apellido %></p>
<p><strong>Teléfono:</strong> <%= @cliente.telefono %></p>
<p><strong>DNI:</strong> <%= @cliente.dni %></p>
<p><strong>Email:</strong> <%= @cliente.email %></p>

<%= link_to 'Editar mis datos', edit_cliente_path(@cliente), class: "btn btn-warning" %> |
<%= link_to 'Volver a la lista de Clientes', clientes_path, class: "btn btn-secondary" %> |
<%= link_to 'Ver Empleados', empleados_path, class: "btn btn-success" %>

app/views/clientes/update.html.erb
<h1>Clientes#update</h1>
<p>Find me in app/views/clientes/update.html.erb</p>

app/views/detalle_pedidos/show.html.erb
<h1>Detalles del Pedido</h1>
<p><strong>Fecha del Pedido:</strong> <%= @pedido.fecha_pedido %></p>
<p><strong>Cliente:</strong> <%= @cliente.nombre %></p>
<p><strong>Empleado:</strong> <%= @empleado.nombre %></p>
<p><strong>Producto:</strong> <%= @producto.nombre_producto %></p>
<p><strong>Cantidad:</strong> <%= @pedido.cantidad %></p>
<p><strong>Precio Unitario:</strong> <%= number_to_currency(@detalle_pedido.precio_unitario) %></p>
<p><strong>Subtotal:</strong> <%= number_to_currency(@detalle_pedido.subtotal) %></p>

app/views/empleados/index.html.erb
<%= stylesheet_link_tag 'empleados/empleados_lista', media: 'all' %>
<h1>Lista de Empleados</h1>
<table>
  <tr>
    <th>Nombre</th>
    <th>Cargo</th>
  </tr>
  <% @empleados.each do |empleado| %>
    <tr>
      <td><%= link_to empleado.nombre, empleado_path(empleado) %></td>
      <td><%= empleado.cargo %></td>
    </tr>
  <% end %>
</table>

app/views/empleados/show.html.erb
<%= stylesheet_link_tag 'empleados/empleados_detail', media: 'all' %>
<h1>Detalles del Empleado</h1>
<p><strong>Nombre:</strong> <%= @empleado.nombre %></p>
<p><strong>Apellido:</strong> <%= @empleado.apellido %></p>
<p><strong>Teléfono:</strong> <%= @empleado.telefono %></p>
<p><strong>Correo:</strong> <%= @empleado.correo %></p>
<p><strong>Fecha de Contratación:</strong> <%= @empleado.fechas_contratacion %></p>
<p><strong>Cargo:</strong> <%= @empleado.cargo %></p>

<%= link_to 'Regresar', empleados_path, class: "btn btn-success" %> |
<%= link_to 'Confirmar y ver productos', productos_path, class: "btn btn-success" %>

app/views/pedidos/create.html.erb
<h1>Pedidos#create</h1>
<p>Find me in app/views/pedidos/create.html.erb</p>

app/views/pedidos/new.html.erb
<%= stylesheet_link_tag 'pedidos/pedidos_new', media: 'all' %>

<h1>Realice su pedido</h1>

<%= form_with(model: @pedido, local: true) do |form| %>  <!-- Crea un nuevo formulario para pedido -->
    <div>
      <%= form.label :producto_id %>
      <%= form.collection_select :producto_id, @productos, :id, :nombre_producto, prompt: 'Selecciona un producto' %>
      <!-- Genera menú desplegable para producto más una opcion vacia -->
    </div>
  
    <div>
      <%= form.label :fecha_pedido %>
      <%= form.date_field :fecha_pedido %>
    </div>
  
    <div>
      <%= form.label :cliente_id %>
      <%= form.number_field :cliente_id %>
    </div>
  
    <div>
      <%= form.label :empleado_id %>
      <%= form.number_field :empleado_id %>
    </div>
  
    <div>
      <%= form.label :cantidad %>
      <%= form.number_field :cantidad %>
    </div>
  
    <div>
      <%= form.submit 'Crear Pedido' %>
    </div>
  <% end %>
  

app/views/pedidos/show.html.erb
<%= stylesheet_link_tag 'pedidos/pedidos_detail', media: 'all' %>

<div class="table-container">
    <h1>Detalles del Pedido</h1>

    <table>
        <tr>
            <th>ID del Pedido</th>
            <td><%= @pedido.id %></td>
        </tr>
        <tr>
            <th>Fecha del Pedido</th>
            <td><%= @pedido.fecha_pedido %></td>
        </tr>
        <tr>
            <th>Cliente</th>
            <td><%= @cliente.nombre %></td>
        </tr>
        <tr>
            <th>Empleado</th>
            <td><%= @empleado.nombre %></td>
        </tr>
        <tr>
            <th>Producto</th>
            <td><%= @producto.nombre_producto %></td>
        </tr>
        <tr>
            <th>Cantidad</th>
            <td><%= @pedido.cantidad %></td>
        </tr>
        <tr>
            <th>Precio Unitario</th>
            <td><%= number_to_currency(@pedido.precio_unitario) %></td>   
        </tr>
        <tr>
            <th>Subtotal</th>
            <td><%= number_to_currency(@pedido.subtotal) %></td>
        </tr>
    </table>

</div>

app/views/productos/index.html.erb
<%= stylesheet_link_tag 'productos/productos_lista', media: 'all' %>
<h1>Lista de Productos</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Precio</th>
  </tr>
  <% @productos.each do |producto| %>      <!-- Crea un tabla para cada producto -->
    <tr>
      <td><%= producto.id %></td>
      <td><%= link_to producto.nombre_producto, producto_path(producto) %></td>  <!-- Nombre con enlace a detalles del producto--> 
      <td><%= number_to_currency(producto.precio) %></td>  <!-- Mostrar precio como moneda -->
    </tr>
  <% end %>
</table>

app/views/productos/show.html.erb
<%= stylesheet_link_tag 'productos/productos_detail', media: 'all' %>
<h1>Detalles del Producto</h1>
<p><strong>Nombre del Producto:</strong> <%= @producto.nombre_producto %></p>      <!-- Recupera los datos del producto --> 
<p><strong>Precio:</strong> <%= number_to_currency(@producto.precio) %></p>
<p><strong>Stock:</strong> <%= @producto.stock %></p>
<p><strong>Descripción:</strong> <%= @producto.descripcion %></p>
<p><strong>Proveedor:</strong> <%= @producto.proveedor.nombre_proveedor %></p>
<!-- Muestra el nombre del proveedor asociado con el producto. -->
<!-- Esto se accede a través de la relación entre el modelo Producto y el modelo Proveedor. -->

<%= link_to 'Ir a la página de Pedidos', new_pedido_path, class: "btn btn-primary" %> <!-- Link para la página de pedidos -->

app/views/proveedores/index.html.erb
<%= stylesheet_link_tag 'proveedor/proveedor_lista', media: 'all' %>
<h1>Lista de Proveedores</h1>
<table>
  <tr>
    <th>Nombre del Proveedor</th>
    <th>Contacto</th>
    <th>Teléfono</th>
    <th>Correo</th>
  </tr>
  <% @proveedores.each do |proveedor| %>
    <tr>
      <td><%= proveedor.nombre_proveedor %></td>
      <td><%= proveedor.contacto %></td>
      <td><%= proveedor.telefono %></td>
      <td><%= proveedor.correo %></td>
    </tr>
  <% end %>
</table>